// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: breafcaseserver.proto

#include "breafcaseserver.pb.h"
#include "breafcaseserver.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace backendservice {

static const char* PostBriefcaseService_method_names[] = {
  "/backendservice.PostBriefcaseService/addCsv",
};

std::unique_ptr< PostBriefcaseService::Stub> PostBriefcaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PostBriefcaseService::Stub> stub(new PostBriefcaseService::Stub(channel, options));
  return stub;
}

PostBriefcaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_addCsv_(PostBriefcaseService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PostBriefcaseService::Stub::addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addCsv_, context, request, response);
}

void PostBriefcaseService::Stub::async::addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addCsv_, context, request, response, std::move(f));
}

void PostBriefcaseService::Stub::async::addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addCsv_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PostBriefcaseService::Stub::PrepareAsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::backendservice::BriefcaseCSVResponse, ::backendservice::BriefcaseCSVRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addCsv_, context, request);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PostBriefcaseService::Stub::AsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddCsvRaw(context, request, cq);
  result->StartCall();
  return result;
}

PostBriefcaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PostBriefcaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PostBriefcaseService::Service, ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PostBriefcaseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::backendservice::BriefcaseCSVRequest* req,
             ::backendservice::BriefcaseCSVResponse* resp) {
               return service->addCsv(ctx, req, resp);
             }, this)));
}

PostBriefcaseService::Service::~Service() {
}

::grpc::Status PostBriefcaseService::Service::addCsv(::grpc::ServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* PutBriefcaseService_method_names[] = {
  "/backendservice.PutBriefcaseService/updateBreafecase",
};

std::unique_ptr< PutBriefcaseService::Stub> PutBriefcaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PutBriefcaseService::Stub> stub(new PutBriefcaseService::Stub(channel, options));
  return stub;
}

PutBriefcaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_updateBreafecase_(PutBriefcaseService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PutBriefcaseService::Stub::updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_updateBreafecase_, context, request, response);
}

void PutBriefcaseService::Stub::async::updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updateBreafecase_, context, request, response, std::move(f));
}

void PutBriefcaseService::Stub::async::updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updateBreafecase_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PutBriefcaseService::Stub::PrepareAsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::backendservice::BriefcaseCSVResponse, ::backendservice::BriefcaseCSVRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_updateBreafecase_, context, request);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PutBriefcaseService::Stub::AsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupdateBreafecaseRaw(context, request, cq);
  result->StartCall();
  return result;
}

PutBriefcaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PutBriefcaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PutBriefcaseService::Service, ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PutBriefcaseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::backendservice::BriefcaseCSVRequest* req,
             ::backendservice::BriefcaseCSVResponse* resp) {
               return service->updateBreafecase(ctx, req, resp);
             }, this)));
}

PutBriefcaseService::Service::~Service() {
}

::grpc::Status PutBriefcaseService::Service::updateBreafecase(::grpc::ServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* BriefcaseService_method_names[] = {
  "/backendservice.BriefcaseService/getBreifcaseInfo",
};

std::unique_ptr< BriefcaseService::Stub> BriefcaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BriefcaseService::Stub> stub(new BriefcaseService::Stub(channel, options));
  return stub;
}

BriefcaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getBreifcaseInfo_(BriefcaseService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BriefcaseService::Stub::getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::backendservice::BriefcaseInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getBreifcaseInfo_, context, request, response);
}

void BriefcaseService::Stub::async::getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getBreifcaseInfo_, context, request, response, std::move(f));
}

void BriefcaseService::Stub::async::getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getBreifcaseInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>* BriefcaseService::Stub::PrepareAsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::backendservice::BriefcaseInfoResponse, ::backendservice::BriefcaseInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getBreifcaseInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>* BriefcaseService::Stub::AsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetBreifcaseInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

BriefcaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BriefcaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BriefcaseService::Service, ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BriefcaseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::backendservice::BriefcaseInfoRequest* req,
             ::backendservice::BriefcaseInfoResponse* resp) {
               return service->getBreifcaseInfo(ctx, req, resp);
             }, this)));
}

BriefcaseService::Service::~Service() {
}

::grpc::Status BriefcaseService::Service::getBreifcaseInfo(::grpc::ServerContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* PostRecomendedValuesService_method_names[] = {
  "/backendservice.PostRecomendedValuesService/addRecomendedValues",
};

std::unique_ptr< PostRecomendedValuesService::Stub> PostRecomendedValuesService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PostRecomendedValuesService::Stub> stub(new PostRecomendedValuesService::Stub(channel, options));
  return stub;
}

PostRecomendedValuesService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_addRecomendedValues_(PostRecomendedValuesService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PostRecomendedValuesService::Stub::addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::backendservice::RecomendedValuesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addRecomendedValues_, context, request, response);
}

void PostRecomendedValuesService::Stub::async::addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addRecomendedValues_, context, request, response, std::move(f));
}

void PostRecomendedValuesService::Stub::async::addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addRecomendedValues_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>* PostRecomendedValuesService::Stub::PrepareAsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::backendservice::RecomendedValuesResponse, ::backendservice::RecomendedValuesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addRecomendedValues_, context, request);
}

::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>* PostRecomendedValuesService::Stub::AsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddRecomendedValuesRaw(context, request, cq);
  result->StartCall();
  return result;
}

PostRecomendedValuesService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PostRecomendedValuesService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PostRecomendedValuesService::Service, ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PostRecomendedValuesService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::backendservice::RecomendedValuesRequest* req,
             ::backendservice::RecomendedValuesResponse* resp) {
               return service->addRecomendedValues(ctx, req, resp);
             }, this)));
}

PostRecomendedValuesService::Service::~Service() {
}

::grpc::Status PostRecomendedValuesService::Service::addRecomendedValues(::grpc::ServerContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace backendservice

