// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: portfolio.proto
// Protobuf C++ Version: 5.27.2

#include "portfolio.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace backendservice {

inline constexpr RecomendedValuesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecomendedValuesResponse::RecomendedValuesResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecomendedValuesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecomendedValuesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecomendedValuesResponseDefaultTypeInternal() {}
  union {
    RecomendedValuesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecomendedValuesResponseDefaultTypeInternal _RecomendedValuesResponse_default_instance_;

inline constexpr RecomendedValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dateofpurchase_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        price_{::int64_t{0}},
        count_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecomendedValue::RecomendedValue(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecomendedValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecomendedValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecomendedValueDefaultTypeInternal() {}
  union {
    RecomendedValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecomendedValueDefaultTypeInternal _RecomendedValue_default_instance_;

inline constexpr PortfolioInfoRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : infotype_{static_cast< ::backendservice::EInfoType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioInfoRequest::PortfolioInfoRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PortfolioInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioInfoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioInfoRequestDefaultTypeInternal() {}
  union {
    PortfolioInfoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioInfoRequestDefaultTypeInternal _PortfolioInfoRequest_default_instance_;

inline constexpr PortfolioCSVResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioCSVResponse::PortfolioCSVResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PortfolioCSVResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioCSVResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioCSVResponseDefaultTypeInternal() {}
  union {
    PortfolioCSVResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioCSVResponseDefaultTypeInternal _PortfolioCSVResponse_default_instance_;

inline constexpr PortfolioCSVRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioCSVRequest::PortfolioCSVRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PortfolioCSVRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioCSVRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioCSVRequestDefaultTypeInternal() {}
  union {
    PortfolioCSVRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioCSVRequestDefaultTypeInternal _PortfolioCSVRequest_default_instance_;

inline constexpr DataInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dateofpurchase_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        priceofpurchase_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pricecurrent_{::int64_t{0}},
        count_{0},
        prediction_{static_cast< ::backendservice::EPrediction >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DataInfo::DataInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DataInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataInfoDefaultTypeInternal() {}
  union {
    DataInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataInfoDefaultTypeInternal _DataInfo_default_instance_;

inline constexpr RecomendedValuesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : values_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecomendedValuesRequest::RecomendedValuesRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecomendedValuesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecomendedValuesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecomendedValuesRequestDefaultTypeInternal() {}
  union {
    RecomendedValuesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecomendedValuesRequestDefaultTypeInternal _RecomendedValuesRequest_default_instance_;

inline constexpr PortfolioInfoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : infos_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioInfoResponse::PortfolioInfoResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PortfolioInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioInfoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioInfoResponseDefaultTypeInternal() {}
  union {
    PortfolioInfoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioInfoResponseDefaultTypeInternal _PortfolioInfoResponse_default_instance_;
}  // namespace backendservice
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_portfolio_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_portfolio_2eproto = nullptr;
const ::uint32_t
    TableStruct_portfolio_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.dateofpurchase_),
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.priceofpurchase_),
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.count_),
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.pricecurrent_),
        PROTOBUF_FIELD_OFFSET(::backendservice::DataInfo, _impl_.prediction_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVRequest, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVRequest, _impl_.content_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioCSVResponse, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioInfoRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioInfoRequest, _impl_.infotype_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioInfoResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::PortfolioInfoResponse, _impl_.infos_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValue, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValue, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValue, _impl_.dateofpurchase_),
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValue, _impl_.count_),
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValue, _impl_.price_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValuesRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValuesRequest, _impl_.values_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValuesResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::backendservice::RecomendedValuesResponse, _impl_.status_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::backendservice::DataInfo)},
        {14, -1, -1, sizeof(::backendservice::PortfolioCSVRequest)},
        {24, -1, -1, sizeof(::backendservice::PortfolioCSVResponse)},
        {34, -1, -1, sizeof(::backendservice::PortfolioInfoRequest)},
        {43, -1, -1, sizeof(::backendservice::PortfolioInfoResponse)},
        {52, -1, -1, sizeof(::backendservice::RecomendedValue)},
        {64, -1, -1, sizeof(::backendservice::RecomendedValuesRequest)},
        {73, -1, -1, sizeof(::backendservice::RecomendedValuesResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::backendservice::_DataInfo_default_instance_._instance,
    &::backendservice::_PortfolioCSVRequest_default_instance_._instance,
    &::backendservice::_PortfolioCSVResponse_default_instance_._instance,
    &::backendservice::_PortfolioInfoRequest_default_instance_._instance,
    &::backendservice::_PortfolioInfoResponse_default_instance_._instance,
    &::backendservice::_RecomendedValue_default_instance_._instance,
    &::backendservice::_RecomendedValuesRequest_default_instance_._instance,
    &::backendservice::_RecomendedValuesResponse_default_instance_._instance,
};
const char descriptor_table_protodef_portfolio_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017portfolio.proto\022\016backendservice\"\237\001\n\010Da"
    "taInfo\022\014\n\004name\030\001 \001(\t\022\026\n\016dateOfPurchase\030\002"
    " \001(\t\022\027\n\017priceOfPurchase\030\003 \001(\t\022\r\n\005count\030\004"
    " \001(\005\022\024\n\014priceCurrent\030\005 \001(\003\022/\n\nprediction"
    "\030\006 \001(\0162\033.backendservice.EPrediction\"8\n\023P"
    "ortfolioCSVRequest\022\020\n\010filename\030\001 \001(\t\022\017\n\007"
    "content\030\002 \001(\014\"8\n\024PortfolioCSVResponse\022\017\n"
    "\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"C\n\024Portf"
    "olioInfoRequest\022+\n\010infoType\030\001 \001(\0162\031.back"
    "endservice.EInfoType\"@\n\025PortfolioInfoRes"
    "ponse\022\'\n\005infos\030\001 \003(\0132\030.backendservice.Da"
    "taInfo\"U\n\017RecomendedValue\022\014\n\004name\030\001 \001(\t\022"
    "\026\n\016dateOfPurchase\030\002 \001(\t\022\r\n\005count\030\003 \001(\005\022\r"
    "\n\005price\030\004 \001(\003\"J\n\027RecomendedValuesRequest"
    "\022/\n\006values\030\001 \003(\0132\037.backendservice.Recome"
    "ndedValue\"*\n\030RecomendedValuesResponse\022\016\n"
    "\006status\030\001 \001(\t*,\n\tEInfoType\022\010\n\004FULL\020\000\022\t\n\005"
    "RISED\020\002\022\n\n\006FALLEN\020\003*3\n\013EPrediction\022\010\n\004ST"
    "AY\020\000\022\010\n\004SELL\020\001\022\020\n\014UNPROFITABLE\020\0022\217\003\n\020Por"
    "tfolioService\022T\n\007postCsv\022#.backendservic"
    "e.PortfolioCSVRequest\032$.backendservice.P"
    "ortfolioCSVResponse\022Z\n\rputBreafecase\022#.b"
    "ackendservice.PortfolioCSVRequest\032$.back"
    "endservice.PortfolioCSVResponse\022_\n\020getBr"
    "eifcaseInfo\022$.backendservice.PortfolioIn"
    "foRequest\032%.backendservice.PortfolioInfo"
    "Response\022h\n\023addRecomendedValues\022\'.backen"
    "dservice.RecomendedValuesRequest\032(.backe"
    "ndservice.RecomendedValuesResponseb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_portfolio_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_portfolio_2eproto = {
    false,
    false,
    1162,
    descriptor_table_protodef_portfolio_2eproto,
    "portfolio.proto",
    &descriptor_table_portfolio_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_portfolio_2eproto::offsets,
    file_level_enum_descriptors_portfolio_2eproto,
    file_level_service_descriptors_portfolio_2eproto,
};
namespace backendservice {
const ::google::protobuf::EnumDescriptor* EInfoType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_portfolio_2eproto);
  return file_level_enum_descriptors_portfolio_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EInfoType_internal_data_[] = {
    65536u, 32u, 6u, };
bool EInfoType_IsValid(int value) {
  return 0 <= value && value <= 3 && ((13u >> value) & 1) != 0;
}
const ::google::protobuf::EnumDescriptor* EPrediction_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_portfolio_2eproto);
  return file_level_enum_descriptors_portfolio_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t EPrediction_internal_data_[] = {
    196608u, 0u, };
bool EPrediction_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class DataInfo::_Internal {
 public:
};

DataInfo::DataInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.DataInfo)
}
inline PROTOBUF_NDEBUG_INLINE DataInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::DataInfo& from_msg)
      : name_(arena, from.name_),
        dateofpurchase_(arena, from.dateofpurchase_),
        priceofpurchase_(arena, from.priceofpurchase_),
        _cached_size_{0} {}

DataInfo::DataInfo(
    ::google::protobuf::Arena* arena,
    const DataInfo& from)
    : ::google::protobuf::Message(arena) {
  DataInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pricecurrent_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pricecurrent_),
           offsetof(Impl_, prediction_) -
               offsetof(Impl_, pricecurrent_) +
               sizeof(Impl_::prediction_));

  // @@protoc_insertion_point(copy_constructor:backendservice.DataInfo)
}
inline PROTOBUF_NDEBUG_INLINE DataInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        dateofpurchase_(arena),
        priceofpurchase_(arena),
        _cached_size_{0} {}

inline void DataInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pricecurrent_),
           0,
           offsetof(Impl_, prediction_) -
               offsetof(Impl_, pricecurrent_) +
               sizeof(Impl_::prediction_));
}
DataInfo::~DataInfo() {
  // @@protoc_insertion_point(destructor:backendservice.DataInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DataInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.dateofpurchase_.Destroy();
  _impl_.priceofpurchase_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DataInfo::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DataInfo, _impl_._cached_size_),
              false,
          },
          &DataInfo::MergeImpl,
          &DataInfo::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 65, 2> DataInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DataInfo_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::DataInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.name_)}},
    // string dateOfPurchase = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.dateofpurchase_)}},
    // string priceOfPurchase = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.priceofpurchase_)}},
    // int32 count = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DataInfo, _impl_.count_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.count_)}},
    // int64 priceCurrent = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DataInfo, _impl_.pricecurrent_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.pricecurrent_)}},
    // .backendservice.EPrediction prediction = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DataInfo, _impl_.prediction_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.prediction_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string dateOfPurchase = 2;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.dateofpurchase_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string priceOfPurchase = 3;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.priceofpurchase_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 count = 4;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 priceCurrent = 5;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.pricecurrent_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .backendservice.EPrediction prediction = 6;
    {PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.prediction_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\27\4\16\17\0\0\0\0"
    "backendservice.DataInfo"
    "name"
    "dateOfPurchase"
    "priceOfPurchase"
  }},
};

PROTOBUF_NOINLINE void DataInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.DataInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.dateofpurchase_.ClearToEmpty();
  _impl_.priceofpurchase_.ClearToEmpty();
  ::memset(&_impl_.pricecurrent_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.prediction_) -
      reinterpret_cast<char*>(&_impl_.pricecurrent_)) + sizeof(_impl_.prediction_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DataInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.DataInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.DataInfo.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string dateOfPurchase = 2;
  if (!this->_internal_dateofpurchase().empty()) {
    const std::string& _s = this->_internal_dateofpurchase();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.DataInfo.dateOfPurchase");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string priceOfPurchase = 3;
  if (!this->_internal_priceofpurchase().empty()) {
    const std::string& _s = this->_internal_priceofpurchase();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.DataInfo.priceOfPurchase");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 count = 4;
  if (this->_internal_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_count(), target);
  }

  // int64 priceCurrent = 5;
  if (this->_internal_pricecurrent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<5>(
            stream, this->_internal_pricecurrent(), target);
  }

  // .backendservice.EPrediction prediction = 6;
  if (this->_internal_prediction() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        6, this->_internal_prediction(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.DataInfo)
  return target;
}

::size_t DataInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.DataInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string dateOfPurchase = 2;
  if (!this->_internal_dateofpurchase().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_dateofpurchase());
  }

  // string priceOfPurchase = 3;
  if (!this->_internal_priceofpurchase().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_priceofpurchase());
  }

  // int64 priceCurrent = 5;
  if (this->_internal_pricecurrent() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_pricecurrent());
  }

  // int32 count = 4;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_count());
  }

  // .backendservice.EPrediction prediction = 6;
  if (this->_internal_prediction() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_prediction());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DataInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DataInfo*>(&to_msg);
  auto& from = static_cast<const DataInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.DataInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_dateofpurchase().empty()) {
    _this->_internal_set_dateofpurchase(from._internal_dateofpurchase());
  }
  if (!from._internal_priceofpurchase().empty()) {
    _this->_internal_set_priceofpurchase(from._internal_priceofpurchase());
  }
  if (from._internal_pricecurrent() != 0) {
    _this->_impl_.pricecurrent_ = from._impl_.pricecurrent_;
  }
  if (from._internal_count() != 0) {
    _this->_impl_.count_ = from._impl_.count_;
  }
  if (from._internal_prediction() != 0) {
    _this->_impl_.prediction_ = from._impl_.prediction_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DataInfo::CopyFrom(const DataInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.DataInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DataInfo::InternalSwap(DataInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dateofpurchase_, &other->_impl_.dateofpurchase_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.priceofpurchase_, &other->_impl_.priceofpurchase_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.prediction_)
      + sizeof(DataInfo::_impl_.prediction_)
      - PROTOBUF_FIELD_OFFSET(DataInfo, _impl_.pricecurrent_)>(
          reinterpret_cast<char*>(&_impl_.pricecurrent_),
          reinterpret_cast<char*>(&other->_impl_.pricecurrent_));
}

::google::protobuf::Metadata DataInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PortfolioCSVRequest::_Internal {
 public:
};

PortfolioCSVRequest::PortfolioCSVRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.PortfolioCSVRequest)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioCSVRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::PortfolioCSVRequest& from_msg)
      : filename_(arena, from.filename_),
        content_(arena, from.content_),
        _cached_size_{0} {}

PortfolioCSVRequest::PortfolioCSVRequest(
    ::google::protobuf::Arena* arena,
    const PortfolioCSVRequest& from)
    : ::google::protobuf::Message(arena) {
  PortfolioCSVRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:backendservice.PortfolioCSVRequest)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioCSVRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        content_(arena),
        _cached_size_{0} {}

inline void PortfolioCSVRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PortfolioCSVRequest::~PortfolioCSVRequest() {
  // @@protoc_insertion_point(destructor:backendservice.PortfolioCSVRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PortfolioCSVRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.content_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PortfolioCSVRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PortfolioCSVRequest, _impl_._cached_size_),
              false,
          },
          &PortfolioCSVRequest::MergeImpl,
          &PortfolioCSVRequest::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 51, 2> PortfolioCSVRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PortfolioCSVRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::PortfolioCSVRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes content = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioCSVRequest, _impl_.content_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioCSVRequest, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioCSVRequest, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes content = 2;
    {PROTOBUF_FIELD_OFFSET(PortfolioCSVRequest, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\10\0\0\0\0\0\0"
    "backendservice.PortfolioCSVRequest"
    "filename"
  }},
};

PROTOBUF_NOINLINE void PortfolioCSVRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.PortfolioCSVRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PortfolioCSVRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.PortfolioCSVRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.PortfolioCSVRequest.filename");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes content = 2;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.PortfolioCSVRequest)
  return target;
}

::size_t PortfolioCSVRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.PortfolioCSVRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // bytes content = 2;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PortfolioCSVRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PortfolioCSVRequest*>(&to_msg);
  auto& from = static_cast<const PortfolioCSVRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.PortfolioCSVRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PortfolioCSVRequest::CopyFrom(const PortfolioCSVRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.PortfolioCSVRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioCSVRequest::InternalSwap(PortfolioCSVRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata PortfolioCSVRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PortfolioCSVResponse::_Internal {
 public:
};

PortfolioCSVResponse::PortfolioCSVResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.PortfolioCSVResponse)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioCSVResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::PortfolioCSVResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

PortfolioCSVResponse::PortfolioCSVResponse(
    ::google::protobuf::Arena* arena,
    const PortfolioCSVResponse& from)
    : ::google::protobuf::Message(arena) {
  PortfolioCSVResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:backendservice.PortfolioCSVResponse)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioCSVResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void PortfolioCSVResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
PortfolioCSVResponse::~PortfolioCSVResponse() {
  // @@protoc_insertion_point(destructor:backendservice.PortfolioCSVResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PortfolioCSVResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PortfolioCSVResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PortfolioCSVResponse, _impl_._cached_size_),
              false,
          },
          &PortfolioCSVResponse::MergeImpl,
          &PortfolioCSVResponse::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 51, 2> PortfolioCSVResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PortfolioCSVResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::PortfolioCSVResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioCSVResponse, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PortfolioCSVResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioCSVResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioCSVResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(PortfolioCSVResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\0\7\0\0\0\0\0"
    "backendservice.PortfolioCSVResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void PortfolioCSVResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.PortfolioCSVResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PortfolioCSVResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.PortfolioCSVResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.PortfolioCSVResponse.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.PortfolioCSVResponse)
  return target;
}

::size_t PortfolioCSVResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.PortfolioCSVResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PortfolioCSVResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PortfolioCSVResponse*>(&to_msg);
  auto& from = static_cast<const PortfolioCSVResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.PortfolioCSVResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PortfolioCSVResponse::CopyFrom(const PortfolioCSVResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.PortfolioCSVResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioCSVResponse::InternalSwap(PortfolioCSVResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata PortfolioCSVResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PortfolioInfoRequest::_Internal {
 public:
};

PortfolioInfoRequest::PortfolioInfoRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.PortfolioInfoRequest)
}
PortfolioInfoRequest::PortfolioInfoRequest(
    ::google::protobuf::Arena* arena, const PortfolioInfoRequest& from)
    : PortfolioInfoRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PortfolioInfoRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PortfolioInfoRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.infotype_ = {};
}
PortfolioInfoRequest::~PortfolioInfoRequest() {
  // @@protoc_insertion_point(destructor:backendservice.PortfolioInfoRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PortfolioInfoRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PortfolioInfoRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PortfolioInfoRequest, _impl_._cached_size_),
              false,
          },
          &PortfolioInfoRequest::MergeImpl,
          &PortfolioInfoRequest::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> PortfolioInfoRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PortfolioInfoRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::PortfolioInfoRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .backendservice.EInfoType infoType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PortfolioInfoRequest, _impl_.infotype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioInfoRequest, _impl_.infotype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .backendservice.EInfoType infoType = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioInfoRequest, _impl_.infotype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void PortfolioInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.PortfolioInfoRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.infotype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PortfolioInfoRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.PortfolioInfoRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .backendservice.EInfoType infoType = 1;
  if (this->_internal_infotype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_infotype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.PortfolioInfoRequest)
  return target;
}

::size_t PortfolioInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.PortfolioInfoRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .backendservice.EInfoType infoType = 1;
  if (this->_internal_infotype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_infotype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PortfolioInfoRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PortfolioInfoRequest*>(&to_msg);
  auto& from = static_cast<const PortfolioInfoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.PortfolioInfoRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_infotype() != 0) {
    _this->_impl_.infotype_ = from._impl_.infotype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PortfolioInfoRequest::CopyFrom(const PortfolioInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.PortfolioInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioInfoRequest::InternalSwap(PortfolioInfoRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.infotype_, other->_impl_.infotype_);
}

::google::protobuf::Metadata PortfolioInfoRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PortfolioInfoResponse::_Internal {
 public:
};

PortfolioInfoResponse::PortfolioInfoResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.PortfolioInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::PortfolioInfoResponse& from_msg)
      : infos_{visibility, arena, from.infos_},
        _cached_size_{0} {}

PortfolioInfoResponse::PortfolioInfoResponse(
    ::google::protobuf::Arena* arena,
    const PortfolioInfoResponse& from)
    : ::google::protobuf::Message(arena) {
  PortfolioInfoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:backendservice.PortfolioInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : infos_{visibility, arena},
        _cached_size_{0} {}

inline void PortfolioInfoResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PortfolioInfoResponse::~PortfolioInfoResponse() {
  // @@protoc_insertion_point(destructor:backendservice.PortfolioInfoResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PortfolioInfoResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PortfolioInfoResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PortfolioInfoResponse, _impl_._cached_size_),
              false,
          },
          &PortfolioInfoResponse::MergeImpl,
          &PortfolioInfoResponse::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> PortfolioInfoResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PortfolioInfoResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::PortfolioInfoResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .backendservice.DataInfo infos = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PortfolioInfoResponse, _impl_.infos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .backendservice.DataInfo infos = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioInfoResponse, _impl_.infos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::backendservice::DataInfo>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void PortfolioInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.PortfolioInfoResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.infos_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PortfolioInfoResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.PortfolioInfoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .backendservice.DataInfo infos = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_infos_size());
       i < n; i++) {
    const auto& repfield = this->_internal_infos().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.PortfolioInfoResponse)
  return target;
}

::size_t PortfolioInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.PortfolioInfoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .backendservice.DataInfo infos = 1;
  total_size += 1UL * this->_internal_infos_size();
  for (const auto& msg : this->_internal_infos()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PortfolioInfoResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PortfolioInfoResponse*>(&to_msg);
  auto& from = static_cast<const PortfolioInfoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.PortfolioInfoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_infos()->MergeFrom(
      from._internal_infos());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PortfolioInfoResponse::CopyFrom(const PortfolioInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.PortfolioInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioInfoResponse::InternalSwap(PortfolioInfoResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.infos_.InternalSwap(&other->_impl_.infos_);
}

::google::protobuf::Metadata PortfolioInfoResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecomendedValue::_Internal {
 public:
};

RecomendedValue::RecomendedValue(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.RecomendedValue)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::RecomendedValue& from_msg)
      : name_(arena, from.name_),
        dateofpurchase_(arena, from.dateofpurchase_),
        _cached_size_{0} {}

RecomendedValue::RecomendedValue(
    ::google::protobuf::Arena* arena,
    const RecomendedValue& from)
    : ::google::protobuf::Message(arena) {
  RecomendedValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, price_),
           offsetof(Impl_, count_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::count_));

  // @@protoc_insertion_point(copy_constructor:backendservice.RecomendedValue)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        dateofpurchase_(arena),
        _cached_size_{0} {}

inline void RecomendedValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, count_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::count_));
}
RecomendedValue::~RecomendedValue() {
  // @@protoc_insertion_point(destructor:backendservice.RecomendedValue)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecomendedValue::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.dateofpurchase_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RecomendedValue::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_._cached_size_),
              false,
          },
          &RecomendedValue::MergeImpl,
          &RecomendedValue::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 57, 2> RecomendedValue::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RecomendedValue_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::RecomendedValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 price = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RecomendedValue, _impl_.price_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.price_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.name_)}},
    // string dateOfPurchase = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.dateofpurchase_)}},
    // int32 count = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RecomendedValue, _impl_.count_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.count_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string dateOfPurchase = 2;
    {PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.dateofpurchase_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 count = 3;
    {PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 price = 4;
    {PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\36\4\16\0\0\0\0\0"
    "backendservice.RecomendedValue"
    "name"
    "dateOfPurchase"
  }},
};

PROTOBUF_NOINLINE void RecomendedValue::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.RecomendedValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.dateofpurchase_.ClearToEmpty();
  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.count_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.count_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RecomendedValue::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.RecomendedValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.RecomendedValue.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string dateOfPurchase = 2;
  if (!this->_internal_dateofpurchase().empty()) {
    const std::string& _s = this->_internal_dateofpurchase();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.RecomendedValue.dateOfPurchase");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 count = 3;
  if (this->_internal_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_count(), target);
  }

  // int64 price = 4;
  if (this->_internal_price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<4>(
            stream, this->_internal_price(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.RecomendedValue)
  return target;
}

::size_t RecomendedValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.RecomendedValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string dateOfPurchase = 2;
  if (!this->_internal_dateofpurchase().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_dateofpurchase());
  }

  // int64 price = 4;
  if (this->_internal_price() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_price());
  }

  // int32 count = 3;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RecomendedValue::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecomendedValue*>(&to_msg);
  auto& from = static_cast<const RecomendedValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.RecomendedValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_dateofpurchase().empty()) {
    _this->_internal_set_dateofpurchase(from._internal_dateofpurchase());
  }
  if (from._internal_price() != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (from._internal_count() != 0) {
    _this->_impl_.count_ = from._impl_.count_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecomendedValue::CopyFrom(const RecomendedValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.RecomendedValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecomendedValue::InternalSwap(RecomendedValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dateofpurchase_, &other->_impl_.dateofpurchase_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.count_)
      + sizeof(RecomendedValue::_impl_.count_)
      - PROTOBUF_FIELD_OFFSET(RecomendedValue, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata RecomendedValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecomendedValuesRequest::_Internal {
 public:
};

RecomendedValuesRequest::RecomendedValuesRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.RecomendedValuesRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValuesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::RecomendedValuesRequest& from_msg)
      : values_{visibility, arena, from.values_},
        _cached_size_{0} {}

RecomendedValuesRequest::RecomendedValuesRequest(
    ::google::protobuf::Arena* arena,
    const RecomendedValuesRequest& from)
    : ::google::protobuf::Message(arena) {
  RecomendedValuesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:backendservice.RecomendedValuesRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValuesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : values_{visibility, arena},
        _cached_size_{0} {}

inline void RecomendedValuesRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecomendedValuesRequest::~RecomendedValuesRequest() {
  // @@protoc_insertion_point(destructor:backendservice.RecomendedValuesRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecomendedValuesRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RecomendedValuesRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RecomendedValuesRequest, _impl_._cached_size_),
              false,
          },
          &RecomendedValuesRequest::MergeImpl,
          &RecomendedValuesRequest::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> RecomendedValuesRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_RecomendedValuesRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::RecomendedValuesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .backendservice.RecomendedValue values = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValuesRequest, _impl_.values_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .backendservice.RecomendedValue values = 1;
    {PROTOBUF_FIELD_OFFSET(RecomendedValuesRequest, _impl_.values_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::backendservice::RecomendedValue>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void RecomendedValuesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.RecomendedValuesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.values_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RecomendedValuesRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.RecomendedValuesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .backendservice.RecomendedValue values = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_values_size());
       i < n; i++) {
    const auto& repfield = this->_internal_values().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.RecomendedValuesRequest)
  return target;
}

::size_t RecomendedValuesRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.RecomendedValuesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .backendservice.RecomendedValue values = 1;
  total_size += 1UL * this->_internal_values_size();
  for (const auto& msg : this->_internal_values()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RecomendedValuesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecomendedValuesRequest*>(&to_msg);
  auto& from = static_cast<const RecomendedValuesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.RecomendedValuesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_values()->MergeFrom(
      from._internal_values());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecomendedValuesRequest::CopyFrom(const RecomendedValuesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.RecomendedValuesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecomendedValuesRequest::InternalSwap(RecomendedValuesRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.values_.InternalSwap(&other->_impl_.values_);
}

::google::protobuf::Metadata RecomendedValuesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RecomendedValuesResponse::_Internal {
 public:
};

RecomendedValuesResponse::RecomendedValuesResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backendservice.RecomendedValuesResponse)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValuesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::backendservice::RecomendedValuesResponse& from_msg)
      : status_(arena, from.status_),
        _cached_size_{0} {}

RecomendedValuesResponse::RecomendedValuesResponse(
    ::google::protobuf::Arena* arena,
    const RecomendedValuesResponse& from)
    : ::google::protobuf::Message(arena) {
  RecomendedValuesResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:backendservice.RecomendedValuesResponse)
}
inline PROTOBUF_NDEBUG_INLINE RecomendedValuesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : status_(arena),
        _cached_size_{0} {}

inline void RecomendedValuesResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecomendedValuesResponse::~RecomendedValuesResponse() {
  // @@protoc_insertion_point(destructor:backendservice.RecomendedValuesResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecomendedValuesResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.status_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RecomendedValuesResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RecomendedValuesResponse, _impl_._cached_size_),
              false,
          },
          &RecomendedValuesResponse::MergeImpl,
          &RecomendedValuesResponse::kDescriptorMethods,
          &descriptor_table_portfolio_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 54, 2> RecomendedValuesResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RecomendedValuesResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backendservice::RecomendedValuesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string status = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecomendedValuesResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string status = 1;
    {PROTOBUF_FIELD_OFFSET(RecomendedValuesResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\6\0\0\0\0\0\0"
    "backendservice.RecomendedValuesResponse"
    "status"
  }},
};

PROTOBUF_NOINLINE void RecomendedValuesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:backendservice.RecomendedValuesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RecomendedValuesResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:backendservice.RecomendedValuesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    const std::string& _s = this->_internal_status();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "backendservice.RecomendedValuesResponse.status");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backendservice.RecomendedValuesResponse)
  return target;
}

::size_t RecomendedValuesResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:backendservice.RecomendedValuesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RecomendedValuesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecomendedValuesResponse*>(&to_msg);
  auto& from = static_cast<const RecomendedValuesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:backendservice.RecomendedValuesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecomendedValuesResponse::CopyFrom(const RecomendedValuesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:backendservice.RecomendedValuesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RecomendedValuesResponse::InternalSwap(RecomendedValuesResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
}

::google::protobuf::Metadata RecomendedValuesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace backendservice
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_portfolio_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
