// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: breafcaseserver.proto
#ifndef GRPC_breafcaseserver_2eproto__INCLUDED
#define GRPC_breafcaseserver_2eproto__INCLUDED

#include "breafcaseserver.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace backendservice {

// gRPC сервис
class PostBriefcaseService final {
 public:
  static constexpr char const* service_full_name() {
    return "backendservice.PostBriefcaseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>> AsyncaddCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>>(AsyncaddCsvRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>> PrepareAsyncaddCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>>(PrepareAsyncaddCsvRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>* AsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>* PrepareAsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>> AsyncaddCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>>(AsyncaddCsvRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>> PrepareAsyncaddCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>>(PrepareAsyncaddCsvRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)>) override;
      void addCsv(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* AsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PrepareAsyncaddCsvRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_addCsv_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status addCsv(::grpc::ServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_addCsv() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddCsv(::grpc::ServerContext* context, ::backendservice::BriefcaseCSVRequest* request, ::grpc::ServerAsyncResponseWriter< ::backendservice::BriefcaseCSVResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_addCsv<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_addCsv() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response) { return this->addCsv(context, request, response); }));}
    void SetMessageAllocatorFor_addCsv(
        ::grpc::MessageAllocator< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addCsv(
      ::grpc::CallbackServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_addCsv<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_addCsv() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_addCsv() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddCsv(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_addCsv() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->addCsv(context, request, response); }));
    }
    ~WithRawCallbackMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addCsv(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_addCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_addCsv() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>* streamer) {
                       return this->StreamedaddCsv(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_addCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status addCsv(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedaddCsv(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backendservice::BriefcaseCSVRequest,::backendservice::BriefcaseCSVResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_addCsv<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_addCsv<Service > StreamedService;
};

class PutBriefcaseService final {
 public:
  static constexpr char const* service_full_name() {
    return "backendservice.PutBriefcaseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>> AsyncupdateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>>(AsyncupdateBreafecaseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>> PrepareAsyncupdateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>>(PrepareAsyncupdateBreafecaseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>* AsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseCSVResponse>* PrepareAsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::backendservice::BriefcaseCSVResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>> AsyncupdateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>>(AsyncupdateBreafecaseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>> PrepareAsyncupdateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>>(PrepareAsyncupdateBreafecaseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, std::function<void(::grpc::Status)>) override;
      void updateBreafecase(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* AsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseCSVResponse>* PrepareAsyncupdateBreafecaseRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseCSVRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_updateBreafecase_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status updateBreafecase(::grpc::ServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdateBreafecase(::grpc::ServerContext* context, ::backendservice::BriefcaseCSVRequest* request, ::grpc::ServerAsyncResponseWriter< ::backendservice::BriefcaseCSVResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_updateBreafecase<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backendservice::BriefcaseCSVRequest* request, ::backendservice::BriefcaseCSVResponse* response) { return this->updateBreafecase(context, request, response); }));}
    void SetMessageAllocatorFor_updateBreafecase(
        ::grpc::MessageAllocator< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updateBreafecase(
      ::grpc::CallbackServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_updateBreafecase<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdateBreafecase(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->updateBreafecase(context, request, response); }));
    }
    ~WithRawCallbackMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updateBreafecase(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_updateBreafecase : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_updateBreafecase() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backendservice::BriefcaseCSVRequest, ::backendservice::BriefcaseCSVResponse>* streamer) {
                       return this->StreamedupdateBreafecase(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_updateBreafecase() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status updateBreafecase(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseCSVRequest* /*request*/, ::backendservice::BriefcaseCSVResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedupdateBreafecase(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backendservice::BriefcaseCSVRequest,::backendservice::BriefcaseCSVResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_updateBreafecase<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_updateBreafecase<Service > StreamedService;
};

class BriefcaseService final {
 public:
  static constexpr char const* service_full_name() {
    return "backendservice.BriefcaseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::backendservice::BriefcaseInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>> AsyncgetBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>>(AsyncgetBreifcaseInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>> PrepareAsyncgetBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>>(PrepareAsyncgetBreifcaseInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>* AsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::BriefcaseInfoResponse>* PrepareAsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::backendservice::BriefcaseInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>> AsyncgetBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>>(AsyncgetBreifcaseInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>> PrepareAsyncgetBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>>(PrepareAsyncgetBreifcaseInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void getBreifcaseInfo(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>* AsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backendservice::BriefcaseInfoResponse>* PrepareAsyncgetBreifcaseInfoRaw(::grpc::ClientContext* context, const ::backendservice::BriefcaseInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getBreifcaseInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetBreifcaseInfo(::grpc::ServerContext* context, ::backendservice::BriefcaseInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::backendservice::BriefcaseInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getBreifcaseInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backendservice::BriefcaseInfoRequest* request, ::backendservice::BriefcaseInfoResponse* response) { return this->getBreifcaseInfo(context, request, response); }));}
    void SetMessageAllocatorFor_getBreifcaseInfo(
        ::grpc::MessageAllocator< ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getBreifcaseInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getBreifcaseInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetBreifcaseInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getBreifcaseInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getBreifcaseInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getBreifcaseInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getBreifcaseInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backendservice::BriefcaseInfoRequest, ::backendservice::BriefcaseInfoResponse>* streamer) {
                       return this->StreamedgetBreifcaseInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getBreifcaseInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getBreifcaseInfo(::grpc::ServerContext* /*context*/, const ::backendservice::BriefcaseInfoRequest* /*request*/, ::backendservice::BriefcaseInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetBreifcaseInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backendservice::BriefcaseInfoRequest,::backendservice::BriefcaseInfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getBreifcaseInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getBreifcaseInfo<Service > StreamedService;
};

class PostRecomendedValuesService final {
 public:
  static constexpr char const* service_full_name() {
    return "backendservice.PostRecomendedValuesService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::backendservice::RecomendedValuesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>> AsyncaddRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>>(AsyncaddRecomendedValuesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>> PrepareAsyncaddRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>>(PrepareAsyncaddRecomendedValuesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>* AsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::backendservice::RecomendedValuesResponse>* PrepareAsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::backendservice::RecomendedValuesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>> AsyncaddRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>>(AsyncaddRecomendedValuesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>> PrepareAsyncaddRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>>(PrepareAsyncaddRecomendedValuesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, std::function<void(::grpc::Status)>) override;
      void addRecomendedValues(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>* AsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::backendservice::RecomendedValuesResponse>* PrepareAsyncaddRecomendedValuesRaw(::grpc::ClientContext* context, const ::backendservice::RecomendedValuesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_addRecomendedValues_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status addRecomendedValues(::grpc::ServerContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddRecomendedValues(::grpc::ServerContext* context, ::backendservice::RecomendedValuesRequest* request, ::grpc::ServerAsyncResponseWriter< ::backendservice::RecomendedValuesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_addRecomendedValues<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::backendservice::RecomendedValuesRequest* request, ::backendservice::RecomendedValuesResponse* response) { return this->addRecomendedValues(context, request, response); }));}
    void SetMessageAllocatorFor_addRecomendedValues(
        ::grpc::MessageAllocator< ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addRecomendedValues(
      ::grpc::CallbackServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_addRecomendedValues<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddRecomendedValues(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->addRecomendedValues(context, request, response); }));
    }
    ~WithRawCallbackMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addRecomendedValues(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_addRecomendedValues : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_addRecomendedValues() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::backendservice::RecomendedValuesRequest, ::backendservice::RecomendedValuesResponse>* streamer) {
                       return this->StreamedaddRecomendedValues(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_addRecomendedValues() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status addRecomendedValues(::grpc::ServerContext* /*context*/, const ::backendservice::RecomendedValuesRequest* /*request*/, ::backendservice::RecomendedValuesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedaddRecomendedValues(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::backendservice::RecomendedValuesRequest,::backendservice::RecomendedValuesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_addRecomendedValues<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_addRecomendedValues<Service > StreamedService;
};

}  // namespace backendservice


#endif  // GRPC_breafcaseserver_2eproto__INCLUDED
